# Generated by Django 5.0.2 on 2024-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_max_users_product_min_users_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_users',
            field=models.IntegerField(default=10, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_users',
            field=models.IntegerField(default=1, blank=True, null=True),
        ),
    ]
