# Generated by Django 5.0.2 on 2024-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_max_users_alter_product_min_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_users',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_users',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
