# Generated by Django 5.0.2 on 2024-03-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_user_alter_group_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_users',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
